### PR TITLE
Changing the style for links

### PR DESCRIPTION
**Pull request by ttimsmith**
I'm not really a fan of the yellow background. It's jarring to me. I also did some refactoring in the `_base.scss`.

### CODE REVIEW

**Comment by GarthDB** [comment]
@ttimsmith could you post a screenshot in here?

**Comment by ttimsmith** [comment]
@GarthDB 
apr-29-2016 21-00-23

**Comment by GarthDB** [comment]
It is definitely less jarring and more standard, but I do think we lose a little personality, which the default template doesn't have much to start with.

**Comment by ttimsmith** [comment]
apr-29-2016 21-43-01
 
What about this @GarthDB.

**Comment by GarthDB** [comment]
I like it more. Maybe put the highlight on the default state and add the underline on hover.

The blue could use some contrast from the text color and that could help.

**Comment by GarthDB** [comment]
I just changed the link background color not to end the conversation but to get this pull-request through. If you want to keep chatting about the link color let's start a new issue.

ftba52n5r0

**Pull request merged**
