### PR TITLE
add Usability in Free Software by @jancborchardt

### PR DESCRIPTION
**Pull request by jancborchardt**
Submitting a pull request manually because the resource collector extension failed me for some reason. :\

cc @GarthDB @una @terracomma please review. :)

### CODE REVIEW

**Comment by jancborchardt** [comment]
@una thank you!

When I clicked on the submit button in the resource collector, it just showed the loading animation for a second. Then the submit button was disabled. Nothing happened, no feedback or such. Is that a known issue atm?

**Comment by cmata23x3** [comment]
Sorry about that @jancborchardt, is there any more information that you can share about the error that you experienced? Which method (Chrome Extension, osdrc.herokuapp.com, bookmarklet) did you use to submit the resource?

I was able to submit a [test site](https://github.com/DesignOpen/designopen.github.io/pull/238) a few minutes ago through the Chrome Extension, so it seems the API is working and Heroku hasn't shown any downtime.

**Comment by jancborchardt** [comment]
@cmata23x3 I used the Chrome extension, and sorry there was no more info. I don’t need to log in or fiddle with any settings of the extension, right?

**Comment by cmata23x3** [comment]
@jancborchardt No there isn't anything you need to do other than making sure all the fields are filled in. Not sure how to replicate the bug, but I'll make an issue and we can keep track if this happens again.

**Pull request merged**
