### PR TITLE
added twitter card support to the site

### PR DESCRIPTION
**Pull request by GarthDB**

### CODE REVIEW

**Comment by una** [comment]
:+1:

**Comment by una** [comment]
Is the article added in this PR or in #228?

**Comment by GarthDB** [comment]
yeah, I'll stop the other pr.

**Comment by una** [comment]
Once Travis says yes, I say Yes. :stuck_out_tongue:

**Comment by GarthDB** [comment]
Sorry @una, I keep adding new things. That should be the last of it.

**Comment by una** [comment]
Oh I like the image :) no problem

**Comment by GarthDB** [comment]
Hey @una both failed, but it is because it is linking to a url that won't exist until this pr is published. Go ahead and merge it and I'll look into fixing that bug.

**Comment by GarthDB** [comment]
```
- ./_site/articles/join-us-at-fowd/index.html
  *  External link http://designopen.org/articles/join-us-at-fowd/ failed: 404 No error
rake aborted!
HTML-Proofer found 1 failure!
```

**Pull request merged**
