### PR TITLE
Migrate Travis CI to container-based infrastructure

### PR DESCRIPTION
**Pull request by hughker**
- Per documentation »
http://docs.travis-ci.com/user/migrating-from-legacy/ -- I’ve added the
command to switch to the new infrastructure
- I ran a test here » https://travis-ci.org/hughker/designopen.github.io -- and it passed successfully

### CODE REVIEW

**Comment by GarthDB** [comment]
@hughker I love this, but we can't just disable the external link checker. The site provides a list of resources that are just external links. If external links are broken we should remove those resources.

**Comment by hughker** [comment]
@GarthDB — ahh okay, makes sense. As you'll see here » https://travis-ci.org/DesignOpen/designopen.github.io/builds/75706199#L184-L216 — it's a couple `404` but mainly `302 certificate validation` 

I will try out a couple things and then submit another PR for the upgrade as well as fixing the links… standby.

**Comment by GarthDB** [comment]
@hughker Yeah, I accepted the pr yesterday even with the failing tests because I checked the report and it was all caused by separate issues.

Also, feel free to jump in the [Slack](http://slack.opendesign.foundation) if want to discuss anything.

Thanks so much for the work so far.

**Comment by hughker** [comment]
Closing to make room for new PRs.

**Pull request closed without merging**
